authors:
  foundation:
    name: Hummingbot
    description: Foundation
    avatar: /assets/brand/logo-color.png
    
  coinalpha:
    name: CoinAlpha
    description: Inc.
    avatar: /assets/brand/CA-only.png

  carlo:
    name: Carlo Las Marias
    description: Co-founder, Hummingbot
    avatar: /assets/authors/carlo-las-marias.jpg

  mike:
    name: Michael Feng
    description: Co-founder, Hummingbot
    avatar: /assets/authors/michael-feng.jpg

  martin:
    name: Martin Kou
    description: Co-founder, Hummingbot
    avatar: /assets/authors/martin-kou.jpg

  fede:
    name: Federico Cardoso
    description: CTO, Hummingbot
    avatar: /assets/authors/fede-cardoso.jpg

  community:
    name: Community
    description: Contributor
    avatar: /assets/authors/community-2.webp